Document: config-ovpn
Title: Debian config-ovpn Manual
Author: <insert document author here>
Abstract: This manual describes what config-ovpn is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/config-ovpn/config-ovpn.sgml.gz

Format: postscript
Files: /usr/share/doc/config-ovpn/config-ovpn.ps.gz

Format: text
Files: /usr/share/doc/config-ovpn/config-ovpn.text.gz

Format: HTML
Index: /usr/share/doc/config-ovpn/html/index.html
Files: /usr/share/doc/config-ovpn/html/*.html
